name: TextPlayer
main: TextPlayer.TextPlayer
version: 0.9
author: Codisimus
website: www.codisimus.com
description: Receive text alerts to your phone
commands:
  text:
    description: Main command, type for additional help/commands