name: TextPlayer
main: com.codisimus.plugins.textplayer.TextPlayer
version: 2.4.1
author: Codisimus
website: www.codisimus.com
description: Receive text alerts to your phone
startup: postworld
softdepend: [Vault]
commands:
  text:
    description: Used to setup TextPlayer user settings
    usage: /<command> help
permissions:
  textplayer.text:
    description: Needed to send a Text Message
  textplayer.textadmin:
    description: Needed to send a Text Message to an admin
  textplayer.masstext:
    description: Needed to send a mass Text Message from the Server to all Users
  textplayer.use:
    description: Needed to set your number and receive texts (/text set, /text list, /text limit, /text enable, /text disable, /text whitelist, /text mass)
  textplayer.watch.server:
    description: Needed to receive a text when the Server comes online (/text watch server)
  textplayer.watch.player:
    description: Needed to receive a text when a Player comes online (/text watch player)
  textplayer.watch.everyplayer:
    description: Needed to receive a text when any other Player comes online (/text watch player *)
  textplayer.watch.item:
    description: Needed to receive a text when an itemis placed (/text watch item)
  textplayer.watch.word:
    description: Needed to receive a text when a word is spoken (/text watch word)
  textplayer.watch.errors:
    description: Needed to receive a text when an error is logged
  textplayer.listusers:
    description: Needed to list all of the Users who can receive texts (/text list users)
  textplayer.listadmins:
    description: Needed to list all of the Admins who can receive texts (/text list admins)
  textplayer.free:
    description: Send messages free of charge (Minecraft money, not real money. Messages never cost real money to send)
  textplayer.check:
    description: Allows the Player to tell the TextPlayer plugin to check for new mail (/text check)